[project]
# Project configuration
enable_telemetry = false

[features]
# Enable features
multi_modal = false
persistent_chat = true
readme_as_header = true

[ui]
# UI configuration
name = "Company Intelligence Briefing System"
description = "Get comprehensive intelligence briefings on tracked companies"
show_readme_as_header = true
hide_cot = true

[llm]
# LLM configuration (not used directly, but good for future)
provider = "openai"
model = "gpt-4"
temperature = 0.1
max_tokens = 4000 